### ISSUE TITLE
Feature suggestion: save figures to dedicated folder

### ISSUE THREAD

**Issue by jackobailey** [svmiller/steveproj#5]
Hi Steve,

This is a feature request that may or may not appeal, but I thought would be worth bringing up. Some journals require that figures be sent in a dedicated image folder once the project is accepted. Might this be included either by default or as an option? E.g. on building the project caches all of the images?

**Comment by svmiller** [comment]
The way I do this right now is that the .Rmd file has a chunk that dictates the figures should be saved in a directory called `figs`, which is in the `doc` directory. I'd think that would be one path forward.
