### ISSUE TITLE
Makefile to remove figs generated in docs

### ISSUE THREAD

**Issue by medewitt** [svmiller/steveproj#6]
I recommend adding the following like to your `clean` target in your Makefile just to make sure all the outputs are removed.

```
rm -rf doc/*
```

Also, I would recommend adding

```
.PHONY: clean
```

To the makefile right above the clean target. This is a good practice just in case you ever accidently name a file one of your targets.

**Comment by svmiller** [comment]
Good suggestion since I wrote the pilot Makefile around just the three finished outputs and that approach is just more elegant.

**Comment by svmiller** [comment]
I'm also going to add the data/ directory to it as well.
